# Docker Environment Configuration
spring:
  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      password: test
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:rabbitmq}
    username: admin
    password: admin
    connection-timeout: 60000
    # STOMP over WebSocket을 위한 추가 설정
    stomp:
      host: ${SPRING_RABBITMQ_HOST:rabbitmq}
      port: 61613
      login: admin
      passcode: admin
